# Generated by Django 3.1.3 on 2020-12-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
