# Generated by Django 3.1.3 on 2020-12-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_remove_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.TextField(default='SOME STRING', max_length=50),
        ),
    ]
